version: '3.6'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - listingsApp:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 9331:5432

volumes:
  listingsApp: